### ISSUE TITLE
Slow encryption process on IE and Firefox

### ISSUE THREAD

**Issue by Christewart** [bitcoinjs/bip38#14]
Is there any way to get around the slow encryption process on IE or Mozilla? It takes like 30 to 60 seconds for the encryption to complete.

**Comment by jprichardson** [comment]
Yes, the underlying scrypt implementation could be optimized: https://github.com/cryptocoinjs/scryptsy/issues/3 If you don't care about being `bip38` compliant, but you still care about the encryption, you could alter the `scryptParams` as seen here: https://github.com/bitcoinjs/bip38#scryptparams
