### ISSUE TITLE
api change

### ISSUE THREAD

**Issue by marijnfs** [bitcoinjs/bip38#23]
My code stopped working, did the API change? Could you make clear how to use the library now?

I get:

    var bip38 = new Bip38()
                ^

TypeError: Bip38 is not a function

**Comment by jprichardson** [comment]
Yes. If you want to retain compatibility with your code, you can continue to use 1.x. 2.x changed. See https://github.com/bitcoinjs/bip38#api If you have anymore questions, feel free to ask us.
