### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by grio** [bitcoinjs/bip38#31]
Please tell me the js code is working for the decrypt bip38 function because the code from the current version README.md is not working.
https://github.com/bitcoinjs/bip38/issues/29
https://github.com/bitcoinjs/bip38/issues/30

**Comment by dcousens** [comment]
Resolved in 47cc4ed2a357d8a86fd9768aa9d11bc1a45dae67 and cf50c727773794eaacd0df4643e5d320981cd942

Thanks for reporting @grio

**Comment by grio** [comment]
thank you for the quick support!
