### ISSUE TITLE
Slower than bitaddress.org?

### ISSUE THREAD

**Issue by woodser** [bitcoinjs/bip38#33]
Hi!  I'm seeing this library run about 3x slower than bitaddress.org.  Just curious if others have seen the same and if there's any way / plans to make it run faster while still being BIP38 compliant.  Thanks!

**Comment by dcousens** [comment]
@woodser how are you running it?

**Comment by woodser** [comment]
@dcousens In the browser as a browserified standalone dependency.

**Comment by dcousens** [comment]
Do you have a link to their code?

**Comment by dcousens** [comment]
It may be it that because [scryptsy](https://github.com/cryptocoinjs/scryptsy) is synchronous that it doesn't have the oppurtunity to use the native PBKDF2 in the browser.
I suspect if `scryptsy` was updated to be async-capable,  you would regain your performance loss.

**Comment by woodser** [comment]
Ah, bummer.  Ok, thanks.

**Comment by dcousens** [comment]
@woodser as a maintainer for [scryptsy](https://github.com/cryptocoinjs/scryptsy),  I can happily say,  PRs accepted! :smile:
