### ISSUE TITLE
Testnet support

### ISSUE THREAD

**Issue by shkschneider** [bitcoinjs/bip38#34]
I was using bip38 to add a passphrase to my wif private key.
On testnet3.
Wif: cP9vgjQNxajMj5AhPQwHjywhnRkBmqVyFEJfztbWhnNqmz1GQW1f
Wif (passphrase): 6PYWrxeW1MrM3v7twoJVfBSe2QR6RoFimt5eTQE9nS4mnRyKHVKLaCNqXN
Turns out bitaddress.org tells me the Wif address only is valid on testnet, while the passphrase version works on mainnet and NOT on testnet.
I would expect a testnet address to be valid on testnet and not on maintenant, passphrase or not.

**Comment by shkschneider** [comment]
The issue is related to the wif module, not yours.
I solved my issue by giving as first argument to wif.encode() the network key.

**Comment by dcousens** [comment]
The BIP doesn't mention any network bytes for the encrypted form,  so I think that is the fault of bitaddress.org.

**Comment by shkschneider** [comment]
Indeed. Thanks for the confirmation.
