### ISSUE TITLE
Upgrade to Scryptsy 2.x

### ISSUE THREAD

**Issue by jprichardson** [bitcoinjs/bip38#38]
@ryanzim please have a look at this.

**Comment by woodser** [comment]
Hey guys.  Are you planning to update scryptsy in the near future?  I just finished instrumenting scryptsy in this BIP38 library to be async and am prepping for launch of cryptostorage.com which uses this library.  Just wondering what you guys are planning and what benefit will be gained from it (faster performance, async, etc) as well as expected timeframe if any.  Thanks!

**Comment by RyanZim** [comment]
I'm working on this now.
