### ISSUE TITLE
Poor performance when decrypting 2+ keys

### ISSUE THREAD

**Issue by Rufus-L** [bitcoinjs/bip38#40]
Hey,
I'd like to know why it takes about 2-3s to decrypt one key, but then it gets a lot worse for subsequent keys (12-15s). Is it possible to improve that?

That happens either running with Node or Web browser.
```
var bip38 = require("bip38");
var keyList = ["6PnQYMjJ7ZXpX8rbh8b6PfzK38WG5KL9mGqscB2RXFGb4ZKwXBaP5gMmhC", "6PnPNwvsTy3jeogyENrV23F15om4ecbEmFZcYrjrTsPgvKEwfnubVEAEEc"];
var password = "123";

for (var key of keyList) {
  var t0 = new Date().getTime();
  bip38.decrypt(key, password);
  console.log((new Date().getTime() - t0) + " ms");
}
```

**Comment by dcousens** [comment]
A sample of 2 keys is probably not a great example,  but,  I'd be happy to look into this.  It is likely this is a hot-spotting issue from the VM mis-optimizing the code.

Are you experiencing this consistently?

**Comment by Rufus-L** [comment]
I used a sample of 2 to make the code simpler. The result is always the same: first one is quick, all the others take about 5x the time.

That happens everytime. Even if the 1st and 2nd keys are the same.

**Comment by dcousens** [comment]
Reproduced.
Will investigate...

**Comment by dcousens** [comment]
Closing in favour of https://github.com/cryptocoinjs/scryptsy/issues/8
