### ISSUE TITLE
Add asynchronous support

### ISSUE THREAD

**Issue by woodser** [bitcoinjs/bip38#41]
BIP38 encryption should really be asynchronous.  Otherwise the browser blocks and the user does not receive progress updates until after a key is fully encrypted.

I've implemented asynchronous support bip38 and scryptsy [here](https://github.com/cryptostorage/bip38) and [here](https://github.com/cryptostorage/scryptsy) for consideration.

**Comment by junderw** [comment]
Made an async pull request for scryptsy https://github.com/cryptocoinjs/scryptsy/pull/13

**Comment by junderw** [comment]
It was merged and published in 2.1.0

I can start working on this.

**Comment by junderw** [comment]
Fair warning though... using async on scryptsy decreases performance. (we didn't get some sort of C implementation or WASM or something, we just added await promise setImmediate)

**Comment by junderw** [comment]
WIP that currently has all tests passing for Async methods (does not mean it's safe) is #50 

Let me know if you have any questions and can help review.

**Comment by junderw** [comment]
3.1.0 published
