### ISSUE TITLE
Scryptsy library complications

### ISSUE THREAD

**Issue by pzenger** [bitcoinjs/bip38#46]
Hello, I'm trying to include `bip38` in one of my react-native projects, but since it relies on `scryptsy` which relies on the node  module `crypto` which react-native does not have access to, it is failing.  

From a brief look at this code, it doesn't look like `scryptsy` is actually used anywhere in the code.  Can we remove it as a dependency?

**Comment by junderw** [comment]
6th line of index.js

it is used.

also BIP38 is discouraged for implementation FYI.

It is recommended to use BIP39 + BIP32 + BIP39

**Comment by pzenger** [comment]
@junderw It is being imported on the 6th line of `index.js`, but I do not see that import variable being used anywhere.    

I will look into the combination of BIP39 + BIP32, is there a third you meant to type as well?

**Comment by woodser** [comment]
@junderw Why is BIP38 discouraged for implementation?

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bip38/blob/ebf70644bf7e3d433a728c749b17c48d51afce9d/index.js#L57

**Comment by junderw** [comment]
@woodser https://github.com/bitcoin/bips/wiki/Comments:BIP-0038

**Comment by woodser** [comment]
@junderw Securing a single private key using BIP38 is a valid use case without known fundamental flaws, even according to what you linked (that is, without using a confirmation code).  Single key wallets which re-use a single address can weaken privacy, but re-use is not mandated by BIP38.
